language: node_js
node_js:
  - "node"
  - "5.1"
  - "5"
  - "4.2"
  - "4.1"
  - "4"

sudo: false

os:
  - linux

script:
  - npm test

#before_install:
#  - if [ $TRAVIS_OS_NAME == "linux" ]; then
#      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
#     sh -e /etc/init.d/xvfb start;
#      sleep 3;
#    fi
#
#install:
#  - npm install
#
#script:
#  - npm test --silent